# Generated by Django 4.1.7 on 2023-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publishedDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
